#!/bin/bash

### Variables
#
# Logo key. Use Mod1 for Alt.
set $mod Mod4
# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

set $term alacritty
set $menu fuzzel
set $config_dir ~/.config/sway


### Idle configuration
#
# 5 min → screen off | 10 min → lock | 15 min → suspend
# exec swayidle -w \
#     timeout 300  'swaymsg "output * dpms off"' \
#     timeout 600  'pgrep gtklock || gtklock -d' \
#     timeout 900  'systemctl suspend' \
#     resume       'swaymsg "output * dpms on"' \
#     before-sleep 'pgrep gtklock || gtklock -d'

exec swayidle -w \
    timeout 300   'pgrep swaylock || swaylock -f' \
    timeout 600   'swaymsg "output * dpms off"' \
    resume       'swaymsg "output * dpms on"' \
    timeout 900   'systemctl suspend' \
    before-sleep 'pgrep swaylock || swaylock -f'


### Input configuration
#
# input type:touchpad {
#     dwt enabled
#     tap enabled
#     natural_scroll enabled
#     middle_emulation enabled
# }

input type:keyboard {
    xkb_layout "pt"
    xkb_numlock enabled
    repeat_delay 300
    repeat_rate 50
}

### Appearance
#
# font pango:Lilex Nerd Font Mono 8
font pango:MesloLGS Nerd Font Mono 8

# Colors
include $config_dir/theme/colors.conf

# class                 border   backgr  text    indicator child_border
client.focused          $barbie  $cyan   $fg     $blue     $barbie
client.focused_inactive $gray    $bg     $fg     $bg       $gray
client.unfocused        $gray    $bg     $fg     $bg       $gray
client.urgent           $blue    $blue   $bg     $blue     $blue

# Borders & gaps
default_border pixel 1
default_floating_border pixel 1
titlebar_padding 8 4
gaps inner 0
gaps outer 0

# hold $mod to drag floating windows
floating_modifier $mod normal

# switch to the window's workspace when it requests focus (e.g. clicking a link opens browser on another workspace)
# options: focus | smart (focus if on active workspace, else mark urgent) | urgent | none
focus_on_window_activation focus

### Includes
include $config_dir/keybindings.conf
include $config_dir/rules.conf

### nwg-displays
include $config_dir/workspaces
include $config_dir/outputs

### Autostart
exec_always $config_dir/scripts/autostart.sh
exec $config_dir/scripts/launch-apps.sh

# include /etc/sway/config.d/*
