# Float commonly-floating apps
for_window [app_id="mpv"] floating enable, move position center
for_window [app_id="eog"] floating enable, move position center
for_window [app_id="galculator"] floating enable, resize set 200 400, move position 75 ppt 50 ppt
for_window [app_id="transmission-gtk"] floating enable, move position center
for_window [app_id="nwg-look"] floating enable, move position center
for_window [app_id="pavucontrol"] floating enable, move position center
for_window [app_id="blueman-manager"] floating enable, move position center
for_window [app_id="satty"] floating enable, move position center

for_window [app_id="thunar"] floating enable, move position center
# # Thunar - float dialogs (progress, confirmations, properties, etc.)
# for_window [app_id="thunar" title="File Operation Progress"] floating enable, move position center
# for_window [app_id="thunar" title="Confirm *"] floating enable, move position center
# for_window [app_id="thunar" title="Properties"] floating enable, move position center
# for_window [app_id="thunar" title="Rename *"] floating enable, move position center
# for_window [app_id="thunar" title="Create *"] floating enable, move position center
# for_window [app_id="thunar" title="Error *"] floating enable, move position center
# for_window [app_id="thunar" title="Question *"] floating enable, move position center
# for_window [app_id="thunar" title="Warning *"] floating enable, move position center

# Inhibit idle for fullscreen apps
for_window [app_id=".*"] inhibit_idle fullscreen
