# App workspace assignments
# Workspace 1
assign [app_id="code"] $ws1

# Workspace 2
# assign [app_id="google-chrome"] $ws2

# Workspace 3
# assign [app_id="Alacritty"] $ws3

# Workspace 4

# Workspace 5

# Workspace 6
assign [app_id="gimp"] $ws6
assign [app_id="org.inkscape.Inkscape"] $ws6
assign [app_id="jetbrains-studio"] $ws6
assign [class="(?i)libreoffice.*"] $ws6
assign [app_id="thunderbird"] $ws6
assign [app_id="anydesk"] $ws6

# Workspace 7

# Workspace 8

# Workspace 9
assign [app_id="obsidian"] $ws9
assign [app_id="beekeeper-studio"] $ws9
assign [class="bruno"] $ws9

# Inhibit idle for fullscreen apps
for_window [app_id=".*"] inhibit_idle fullscreen

# Float commonly-floating apps
for_window [app_id="mpv"] floating enable, move position center
for_window [app_id="eog"] floating enable, move position center
for_window [app_id="galculator"] floating enable, resize set 200 400, move position 75 ppt 50 ppt
for_window [app_id="transmission-gtk"] floating enable, move position center
for_window [app_id="nwg-look"] floating enable, move position center
for_window [app_id="pavucontrol"] floating enable, move position center
for_window [app_id="blueman-manager"] floating enable, move position center
for_window [app_id="satty"] floating enable, move position center
for_window [app_id="vlc"] floating enable, move position center

for_window [app_id="thunar"] floating enable, move position center
# # Thunar - float dialogs (progress, confirmations, properties, etc.)
# for_window [app_id="thunar" title="File Operation Progress"] floating enable, move position center
# for_window [app_id="thunar" title="Confirm *"] floating enable, move position center
# for_window [app_id="thunar" title="Properties"] floating enable, move position center
# for_window [app_id="thunar" title="Rename *"] floating enable, move position center
# for_window [app_id="thunar" title="Create *"] floating enable, move position center
# for_window [app_id="thunar" title="Error *"] floating enable, move position center
# for_window [app_id="thunar" title="Question *"] floating enable, move position center
# for_window [app_id="thunar" title="Warning *"] floating enable, move position center

# LibreOffice - float dialogs (import, export, etc.)
for_window [class="(?i)libreoffice.*" title="(?i).*(Import|Export).*"] floating enable

# Android Studio
for_window [app_id="jetbrains-studio" title=".* Wizard"] floating enable, move position center
for_window [app_id="jetbrains-studio" title="Welcome .*"] floating enable, move position center
for_window [app_id="jetbrains-studio" title="New Project"] floating enable
for_window [app_id="jetbrains-studio" title="Device Manager"] floating enable
for_window [app_id="jetbrains-studio" title="Android Emulator .*"] floating enable

# LibreOffice - sway wont move to workspace when floating is enabled
# for_window [class="libreoffice-startcenter"] floating enable, move position center
# for_window [class="libreoffice.*"] floating disable

# Solaar
for_window [app_id="solaar"] floating enable, move position center, resize set height 80 ppt

# nwg-displays
for_window [app_id="nwg-displays"] floating enable, move position center, resize set width 60 ppt

# Xarchive
for_window [app_id="xarchiver"] floating enable, move position center, resize set width 55 ppt height 70 ppt

# Print SetingsP
for_window [app_id="system-config-printer"] floating enable, move position center, resize set width 40 ppt height 60 ppt
