live_config_reload: true
working_directory: '/var/www'

# Themes --
# import: [
#   "~/.config/alacritty/nordic.toml",
#   "~/.config/alacritty/keybinds.toml"
# ]

window:
    # title: 'Alacritty'
    decorations: 'none'
    # opacity: 1
    padding:
        x: 10
        y: 10

    #dimensions:
    #    columns: 160
    #    lines: 80

cursor:
    style:
        shape: 'Beam'
        # blinking: 'Never'

env:
    TERM: 'xterm-256color'

font:
    #glyph_offset: { x: 1, y: 0 }
    normal.family: 'FiraCode Nerd Font'
    size: 16

colors:
    primary:
        background: '#282a36'
        foreground: '#eff0eb'

    cursor:
        cursor: '#97979b'

    selection:
        text: '#282a36'
        background: '#feffff'

    normal:
        black: '#282a36'
        red: '#ff5c57'
        green: '#5af78e'
        yellow: '#f3f99d'
        blue: '#57c7ff'
        magenta: '#ff6ac1'
        cyan: '#9aedfe'
        white: '#f1f1f0'

    bright:
        black: '#686868'
        red: '#ff5c57'
        green: '#5af78e'
        yellow: '#f3f99d'
        blue: '#57c7ff'
        magenta: '#ff6ac1'
        cyan: '#9aedfe'
        white: '#eff0eb'

key_bindings:
    - { key: V, mods: Super, action: Paste }
    - { key: C, mods: Super, action: Copy }
