#!/bin/bash
# notify() {
#     notify-send --icon=office-calendar-symbolic \
#         --hint=string:x-canonical-private-synchronous:"$1" "$@"
# }
# case $BUTTON in
#     1)
#         notify "This Month" "$(cal --color=always |
#             sed "s|..7m|<span>|;s|..0m|</span>|")"
#         appointments="$(calcurse -d1 \
#             --format-apt "• <i>%S - %E</i>\n  <span>%m</span>\n" \
#             --format-event "• <span>%m</span>\n")"
#         [ -n "$appointments" ] && notify "Appointments" "$appointments"
#         ;;
#     2) setsid --fork terminal -e calcurse ;;
#     6) terminal -e "$EDITOR" "$0" ;;
# esac

echo "$(date '+%b %d %H:%M') "
