#!/bin/bash

# Simple script to handle a DIY shutdown menu with rofi.
#
# Requirements:
# - rofi
# - systemd (can be replaced for other init systems if needed)
#
# Instructions:
# - Save this file as power.sh
# - Make it executable: chmod +x /path/to/power.sh
# - Run it

chosen=$(printf '%s\n' "Shutdown" "Reboot" "Logout" "Cancel" | \
    fuzzel --dmenu --prompt "Power: ")

case "$chosen" in
    "Logout")   swaymsg exit ;;
    "Shutdown") systemctl poweroff ;;
    "Reboot")   systemctl reboot ;;
    *)          exit 0 ;;
esac

