#!/bin/bash
if [ "$(nmcli radio wifi)" = "enabled" ]; then
    nmcli radio wifi off
    echo "WiFi: Off"
else
    nmcli radio wifi on &
    swaymsg exec "$HOME/.config/sway/scripts/wifi-connect"
    echo "WiFi: On"
fi
