[main]
font=MesloLGS Nerd Font Mono:size=14
# width=40
# lines=8
horizontal-pad=4s0
vertical-pad=20
inner-pad=10

[main]
filter-desktop=yes

[colors]
background=000000ff
text=d0d7deff
prompt=727272ff
input=ffffffff
match=ffffffff # 8cb8edff
selection=1e1e1eff
selection-text=d0d7deff
selection-match=3584e4ff
# border=ffffffff

[border]
width=0
# radius=8
