; [main]
; font=Sans:size=11
; width=40
; lines=8
; horizontal-pad=20
; vertical-pad=10
; inner-pad=8

[main]
exclude-desktop-files=/usr/share/applications/screensavers

[colors]
background=000000ee
text=ffffffff
match=3584e4ff
selection=3584e4ff
selection-text=ffffffff
; border=ffffffff

; [border]
; width=2
; radius=8
