#!/bin/bash
# Display RAM usage.

case $BUTTON in
	1) notify-send " Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send " Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs.
- Middle click to open htop." ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo " 󰽙 $(free --mebi | sed -n '2{p;q}' | awk '{printf ("%.2fG/%2.0fG\n", ( $3 / 1024), ($2 / 1024))}') "
