[general]
output-filename = "~/Screenshots/%d-%m-%Y_%H%M%S.png"
copy-command = "wl-copy"
early-exit = true
initial-tool = "arrow" 

[color-palette]
palette = [
    "#e31523",
    "#FF9100",
    "#00E676",
    "#29B6F6",
    "#E040FB",
    "#FFFFFF",
    "#000000"
]