# Colors (Nordic)

[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

[colors.normal]
black = '#191C1D'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#B6D7A8'
white = '#BDC5BD'

[colors.bright]
black = '#727C7C'
red = '#c55555'
green = '#BBDA97'
yellow = '#feca88'
blue = '#82b8c8'
magenta = '#c28cb8'
cyan = '#93d3c3'
white = '#f8f8f8'

[colors.selection]
text = '#000000'
background = '#F0DFAF'
